// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqEWMfH4ERkcSn2j_4U0r_97kAGgSw3p0',
    appId: '1:785274935581:web:0865d5529495854ed969f4',
    messagingSenderId: '785274935581',
    projectId: 'spotify-demo-43549',
    authDomain: 'spotify-demo-43549.firebaseapp.com',
    storageBucket: 'spotify-demo-43549.appspot.com',
    measurementId: 'G-QV4ZRK7X50',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdXRXH093IIivXvkYLDU4UJ0EXnmW7Go0',
    appId: '1:785274935581:android:5ff53b857c29877dd969f4',
    messagingSenderId: '785274935581',
    projectId: 'spotify-demo-43549',
    storageBucket: 'spotify-demo-43549.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvyH48BklbQnNutWDtY5Cl3BLOyx6uaUc',
    appId: '1:785274935581:ios:ee2f254e791c75dad969f4',
    messagingSenderId: '785274935581',
    projectId: 'spotify-demo-43549',
    storageBucket: 'spotify-demo-43549.appspot.com',
    iosClientId: '785274935581-kmu7dfu113l3jqgkdfos5eqlokvi3o0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyDemo',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvyH48BklbQnNutWDtY5Cl3BLOyx6uaUc',
    appId: '1:785274935581:ios:ee2f254e791c75dad969f4',
    messagingSenderId: '785274935581',
    projectId: 'spotify-demo-43549',
    storageBucket: 'spotify-demo-43549.appspot.com',
    iosClientId: '785274935581-kmu7dfu113l3jqgkdfos5eqlokvi3o0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyDemo',
  );
}
